### ISSUE TITLE
Link error on Centos 7

### ISSUE THREAD

**Issue by rsinaee** [bobpepin/YacuDecu#1]
Hello:

I am having an issue with linking the library (yacudecu) into my application. I downloaded the binaries packages, and I am using the cufft (version 5.5 downloaded) and yacudecu . I also have  the cudart library linked in. The code compiles fine, but when attempting to link, it always produces the error "undefined reference to `deconv_device(unsigned int, unsigned int, unsigned int, unsigned int, float_, float_, float*)". I am using Eclipse (Luna) as my IDE. any help would be appreciated. Thank you.

Ramin Sinaee

**Comment by bobpepin** [comment]
This sounds like an issue either with your build system or your code. Make sure you are actually linking against libyacudecu.so, and that there are no conflicts with name mangling in case you are using C++ (inspect the library files with nm to see what the symbols look like, then add extern "C" where necessary).
