### ISSUE TITLE
compileXT.m error

### ISSUE THREAD

**Issue by nranthony** [bobpepin/YacuDecu#2]
Hi,
Could you please advise on the below error when compiling in Matlab:
_>> compileXT
Error using loadlibrary
There was an error loading the library "libyacudecu"
The specified module could not be found.
Error in compileXT (line 6)
loadlibrary('libyacudecu','yacudecu.h', 'mfilename', 'yacudecu_proto.m')
Caused by:
    Error using loaddefinedlibrary
    The specified module could not be found._ 

I have downloaded/extracted the required folders and added the following paths in Matlab:
![matlab paths](https://cloud.githubusercontent.com/assets/16306836/21527310/7603bbea-ccf8-11e6-81e4-09816972c4a2.PNG)

Relevant system details:
Win 10 64bit
Imaris 8.4.1
Matlab R2016b
CUDA SDK 8.0

Please let me know if you need further information.
Thanks
Neil

**Comment by bobpepin** [comment]
It can't find libyacudecu.dll, in order to generate the Imaris XTension you first need to compile the yacudecu library itself using Makefile.windows (see README.md). Also note that some paths are hardcoded in compileXT.m you want to adjust these to your setup.

**Comment by nranthony** [comment]
Hi, thanks for the feedback (sorry for the long delay).

I tried to nmake the make file, but received the following:
C:\Users\Admin\Downloads\XTYacuDeconv-1.0\XTYacuDeconv-1.0\src>nmake -f Makefile.windows

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        nvcc -Xcompiler=/LD -O3 -c -o deconv.obj deconv.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
deconv.cu
C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/../../VC/INCLUDE\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.EXE"' : return code '0x2'
Stop.

I don’t want to take up your time, and thank you in advance for looking into these things, but can I please ask if you can help me figure out my problem?  I’m running Win 10 64bit, with CUDA v8.  I added the nmake.exe path to the Path environment in the advanced system properties and ran the nmake command in cmd (as admin) as shown above.

Thanks in advance for your time.

Neil

**Comment by nranthony** [comment]
Also, forgot to mention that I’m running VS Community 2015
Thanks
Neil

From: Anthony, Neil
Sent: Thursday, January 26, 2017 11:17 AM
To: 'bobpepin/YacuDecu' <reply@reply.github.com>; bobpepin/YacuDecu <YacuDecu@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [bobpepin/YacuDecu] compileXT.m error (#2)

Hi, thanks for the feedback (sorry for the long delay).

I tried to nmake the make file, but received the following:
C:\Users\Admin\Downloads\XTYacuDeconv-1.0\XTYacuDeconv-1.0\src>nmake -f Makefile.windows

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        nvcc -Xcompiler=/LD -O3 -c -o deconv.obj deconv.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
deconv.cu
C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/../../VC/INCLUDE\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.EXE"' : return code '0x2'
Stop.

I don’t want to take up your time, and thank you in advance for looking into these things, but can I please ask if you can help me figure out my problem?  I’m running Win 10 64bit, with CUDA v8.  I added the nmake.exe path to the Path environment in the advanced system properties and ran the nmake command in cmd (as admin) as shown above.

Thanks in advance for your time.

Neil
