### ISSUE TITLE
Win 10 64bit, CUDA v8.0, VS Community 2015 makefile troubles

### ISSUE THREAD

**Issue by nranthony** [bobpepin/YacuDecu#3]
Hi, I hope you can please help.

I've had troubles getting the makefile to work on a Win 10 64bit, CUDA v8.0, VS Community 2015 setup.  I'll list the steps I've taken and the things I've tried for completeness:

- added C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin to the Admin Path variable as it wasn't already set by VS2015.  This allowed nmake to be available in cmd.
- following that the nmake returned include file errors (I tried adding C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt and C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um to the INCLUDE system variable but this didn't work.  I copied the files from those directories directly into C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include and it fixed the error)

I now get a "cannot open file uuid.lib" error that I can't figure out.  I tried adding C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\um\x64 and C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\ucrt\x64 to the LIB system variable, but that didn't help.  I don't know where to copy the lib files to for VS to pull them by default?

Thanks in advance for your time.
Neil

**Comment by nranthony** [comment]
Ah, found it:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\amd64 is where is looks for the libraries.  I copied everything from C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\ucrt\x64 and C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\um\x64 and it appears to have worked.

**Comment by nranthony** [comment]
Alas, I now can't get Matlab to compileXT.  I have correct downloads and paths in place.

>> compileXT
Compiler version: 6.3 (R2016b)
Dependency analysis by REQUIREMENTS.
Warning: The following error was caught while executing
'matlab.depfun.internal.DependencyDepot' class destructor:
Error using matlab.depfun.internal.database.SqlDbConnector/disconnect
Attempted to disconnect while transaction was in progress; details: doSql(INSERT INTO
tempFileList (id) SELECT Dependency FROM Proxy_Closure WHERE exists (select 1 from
tempFileList b Where Proxy_Closure.Client = b.id);).

Error in matlab.depfun.internal.DependencyDepot/disconnect (line 83)
                obj.SqlDBConnObj.disconnect();

Error in matlab.depfun.internal.DependencyDepot/delete (line 78)
            obj.disconnect();

Error in matlab.depfun.internal.requirements (line 51)
parts = {};

Error in compileXT (line 9)
mcc -v -m XTYacuDeconv.m -a libyacudecu_thunk_pcwin64.dll -a 'C:\Program Files\NVIDIA GPU
Computing Toolkit\CUDA\v8.0\bin\cufft64_80.dll' -a libyacudecu.dll -a 'C:\Program
Files\Bitplane\Imaris x64 8.4.1\XT\rtmatlab\ImarisLib.jar' 
> In matlab.depfun.internal.requirements (line 51)
  In compileXT (line 9) 
Error using matlab.depfun.internal.database.SqlDbConnector/doSql
Received exception (The database
file:C%3A%5CProgram%20Files%5CMATLAB%5CR2016b%5Ctoolbox%5Cmatlab%5Cdepfun%5C%2Bmatlab%5C%2Bdepfun%5C%2Binternal%5Crequirements%5Fwin64%5Fdfdb?mode=ro
is corrupt. (database disk image is malformed)) upon attempting an operation; details:
doSql(INSERT INTO tempFileList (id) SELECT Dependency FROM Proxy_Closure WHERE exists
(select 1 from tempFileList b Where Proxy_Closure.Client = b.id);).

Error in matlab.depfun.internal.DependencyDepot/requirements (line 620)
            obj.SqlDBConnObj.doSql(idInsertStmt);

Error in matlab.depfun.internal.Completion/retrieveDependencyFromDatabase (line 1931)
                        tmpList = obj.DepDepot.requirements(recentFoundFiles);

Error in matlab.depfun.internal.Completion/computePartsList (line 2016)
                fileList = retrieveDependencyFromDatabase(obj);

Error in matlab.depfun.internal.Completion/requirements (line 2412)
            parts = computePartsList(obj, false);

Error in matlab.depfun.internal.requirements (line 215)
    [parts, resources.products, resources.platforms] = c.requirements();

Error in compileXT (line 9)
mcc -v -m XTYacuDeconv.m -a libyacudecu_thunk_pcwin64.dll -a 'C:\Program Files\NVIDIA GPU
Computing Toolkit\CUDA\v8.0\bin\cufft64_80.dll' -a libyacudecu.dll -a 'C:\Program
Files\Bitplane\Imaris x64 8.4.1\XT\rtmatlab\ImarisLib.jar'
 
Error using mcc
Unexpected error while determining required deployable files. Compilation terminated.

Error in compileXT (line 9)
mcc -v -m XTYacuDeconv.m -a libyacudecu_thunk_pcwin64.dll -a 'C:\Program Files\NVIDIA GPU
Computing Toolkit\CUDA\v8.0\bin\cufft64_80.dll' -a libyacudecu.dll -a 'C:\Program
Files\Bitplane\Imaris x64 8.4.1\XT\rtmatlab\ImarisLib.jar'

**Comment by bobpepin** [comment]
Hi,
this looks like a problem in your matlab setup. I suggest you make sure that your mcc is correctly set up, e.g. by compiling a simple toy example. 
What exactly are you trying to accomplish? compileXT is used to compile the standalone Imaris extension, if this is all you need you should be able to use the binary from the Bitplane XTension webpage.

**Comment by nranthony** [comment]
Hi, and thanks for the speedy reply.

I'll check the compiler as suggested, and I've contacted Mathworks for support.

I tried using the binaries as suggested, but the XTension is greyed out... Do I need to add the newly compiled cuda dll in some way?

Again, thanks for your time.

**Comment by nranthony** [comment]
Hi bobpepin, thanks for your feedback.  I just wanted to let you know the steps I've taken, and what worked and what didn't.

After talking with the speedy/efficient support from Mathworks, it turns out that an uninstall/reinstall fixed the compiler issue.  I can now compile and see the following out in the Matlab command window:
_>> compileXT
Compiler version: 6.3 (R2016b)
Dependency analysis by REQUIREMENTS.
Parsing file "C:\Users\Admin\Google Drive\Data Analysis\Matlab\XTensions\YacuDecu-1.0\XTYacuDeconv.m" 
	(Referenced from: "Compiler Command Line"). 
Deleting 2 temporary MEX authorization files. 
Removing: 'C:\Users\Admin\AppData\Local\Temp\mathworks_tmp_016cc26992_5836.auth'. 
Removing: 'C:\Users\Admin\AppData\Local\Temp\mathworks_tmp_016cc15887_5836.auth'. 
Generating file "C:\Users\Admin\Google Drive\Data Analysis\Matlab\XTensions\YacuDecu-1.0\readme.txt"._ 

I've moved the .exe and .xml files to the rtmatlab folder of Imaris but the CUDA Deconvolution option in the Image Processing menu is still greyed out.  I have both MCR 8.2 and 8.4 installed...  I tried removing 8.4 in case of conflict, but that just greys out all the menu items.

I've also tried using CUDA 7.5, as Mathworks suggested there might be issues with v8, and I get the same result from CompileXT.m, but then it's still greyed out in the menus.

I've also tried the binary from the Bitplane website as you suggest, but it is again greyed out in the menus.

Anything you can think of to try next would be much appreciated.
Thanks

**Comment by bobpepin** [comment]
What happens if you run the .exe file from the command line? Do you get an error message?

**Comment by nranthony** [comment]
I get an error in the Matlab console:

Not enough input arguments.

Error in XTYacuDeconv (line 43)

MATLAB:minrhs

I get the same error if Imaris is running or not.  I get the same error if I compile the exe using mcc with CUDA 7.5 or 8.0.

**Comment by nranthony** [comment]
For completeness, I checked the .exe downloaded directly from Bitplane's XTension webpage, and that gives the same error.  I wonder if it's something to do with the config of the machine here and the Imaris version...?  I'll contact Bitplane again and keep you posted if I find anything out.

Thanks

**Comment by bobpepin** [comment]
Thanks for looking into this, unfortunately I don't have access to an Imaris machine anymore, it would be great if you could get it to run with the latest Imaris.
 If I remember correctly, the .exe needs the "Imaris application id" as argument, try 0,1,2,... and see if you get any further.

**Comment by nranthony** [comment]
Hi, good news.  It works once I install MCR 7.10.  Matt from Bitplane with really helpful, going through all the things he had in place, and that was the only thing I didn't have, and it worked.
Thanks for all your time helping debug.
Neil
