### ISSUE TITLE
python/numpy bindings

### ISSUE THREAD

**Issue by VolkerH** [bobpepin/YacuDecu#4]
Hi, 
just curious whether you are aware of anyone trying to create Python/numpy bindings to YacuDecu. 
I have seen some activity about a Java / ImageJ wrapper, but if there is any activity around Python I couldn't find anything. Just curious whether you are aware of anyone working on this?

**Comment by bobpepin** [comment]
Not aware of anyone doing it, but it should be straightforward to interface with the C api using the standard Python ctypes ffi. An example from a different project with a similar interface, which you should be able to adapt with some inspiration from the matlab interface:

```
import ctypes
import ctypes.util
from ctypes import c_float, c_size_t, c_uint32
import numpy as np

def init_ffi():
    name = ctypes.util.find_library('mminf')
    lib = ctypes.cdll.LoadLibrary(name)
    return lib

libmminf = init_ffi()

# run_mminf C function has signature:
# extern "C" 
# void run_mminf(float lambda, float x0, uint32_t seed, size_t K, float *X, float *clock)
def mminf(lambd, x0, seed, K):
    X = np.empty(K, dtype=np.float32)
    clock = np.empty(K, dtype=np.float32)
    libmminf.run_mminf(c_float(lambd), c_float(x0), c_uint32(seed),
                       c_size_t(K),
                       X.ctypes, clock.ctypes)
    return X, clock
```

**Comment by VolkerH** [comment]
Hi,
thanks for your reply.
 I am aware of ctypes, I was just curious whether you were aware of anyone having already done that and maybe added some python embellishments. I guess the answer is no. For my part I'm happy with the answer ... I just didn't want to set out on recreating work that others may already have done. Will close the issue.

**Comment by bnorthan** [comment]
Hey

Just in case it is still relevant, I've been working on the Java (ImageJ2) wrappers for YacuDecu for a while, and have recently been looking into Python wrappers as well...

There is a Python Wrapper here https://github.com/koschink/PyYacuDecu

Which I've copied code from to make a small wrapper class to my slightly modified version of YacuDecu here https://github.com/imagej/ops-experiments/blob/master/python/deconvolution/YacuDecuUtility.py

Example of using it here https://github.com/imagej/ops-experiments/blob/master/python/deconvolution/DeconSandBox.ipynb

**Comment by VolkerH** [comment]
@bnorthan Thanks ! I will give these a try.
